apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeexpress-1
  namespace: belajar
  labels:
    app: nodeexpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeexpress
  template:
    metadata:
      name: nodeexpress-1
      labels:
        app: nodeexpress
    spec:
      containers:
        - name: nodeexpress-1
          image: rizkypanz/hellonodeexpress:stable
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeexpress-1-service
  namespace: belajar
spec:
  type: LoadBalancer
  selector:
    app: nodeexpress
  ports:
    - port: 3000
      targetPort: 3000
